[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_API_URL = "https://keur-xassida-yi.onrender.com"
  NEXT_PUBLIC_WS_URL = "wss://keur-xassida-yi.onrender.com"
  NEXT_PUBLIC_SUPABASE_URL = "https://jfutcdemqkleebjicxpb.supabase.co"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://keur-xassida-yi.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "https://keur-xassida-yi.onrender.com/media/:splat"
  status = 200
  force = true
