services:
  - type: web
    name: rh-manager-api
    env: docker
    repo: https://github.com/sadekhinformatique/keur-xassida-yi
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/auth/users/
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: USE_DAPHNE
        value: "true"
      - key: RENDER
        value: "true"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: SUPABASE_URL
        value: https://jfutcdemqkleebjicxpb.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_DB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_PORT
        value: "5432"
      - key: DB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
