# Generated by Django 5.1.4 on 2026-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mon Entreprise', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7)),
                ('accent_color', models.CharField(default='#0ea5e9', max_length=7)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('notification_sms', models.BooleanField(default=False)),
                ('auto_generate_qr', models.BooleanField(default=True)),
                ('qr_duration_seconds', models.IntegerField(default=30)),
                ('enable_gps', models.BooleanField(default=False)),
                ('enable_face_recognition', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres entreprise',
                'verbose_name_plural': 'Paramètres entreprise',
            },
        ),
    ]
