# Generated by Django 5.1.4 on 2026-07-06 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'Retard'), ('EARLY_LEAVE', 'Départ anticipé'), ('HOLIDAY', 'Congé')], default='PRESENT', max_length=15)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_info', models.CharField(blank=True, help_text='Infos du téléphone utilisé', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('check_in_method', models.CharField(choices=[('QR_CODE', 'QR Code'), ('MANUAL', 'Manuel'), ('FACE', 'Reconnaissance faciale')], default='QR_CODE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date', '-check_in'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Journal de pointage',
                'verbose_name_plural': 'Journaux de pointage',
                'ordering': ['-timestamp'],
            },
        ),
    ]
